### PR TITLE
Make contact details to show custom information

### PR DESCRIPTION
**Pull request by GPaoloni**
Jira: https://bugs.benetech.org/browse/CHI-335

This PR updates ContactDetails component to consume all of the defined input fields.

Important note: this PR is not taking into consideration form versioning. While The form is saved with the version number (so it can be used in the future), we are now only using the v1 definition to consume the data. This will change soon, when we move to the final structure for fetching definition versions if needed.

### CODE REVIEW

**Review by andvirga — APPROVED** [review]
Looks good! I've tested the "Save contact" functionality and it's working great

**Review by murilovmachado — APPROVED** [review]

**Review by nickhurlburt — APPROVED** [review]
Looks good.  Does this fail for old contacts already stored in the database?

**Comment by GPaoloni** [comment]
@nickhurlburt Yes, it fails, as the "legacy compatibility" has not been included (that's why I understood we wanted from last meeting, but correct me if I'm wrong).

**Comment by nickhurlburt** [comment]
@GPaoloni that's fine, I just wanted to be clear on it.  We just want to be clear to everyone what to expect when this gets merged into staging.

**Pull request merged**
