### PR TITLE
Send the customized form to the backend

### PR DESCRIPTION
**Pull request by GPaoloni**
Jira: https://bugs.benetech.org/browse/CHI-333

This PR modifies the form in local state before sending it to the backend. The only field that is nested at this point is `name` (caller & child info), in order to preserve the current code for search in the backend.

### CODE REVIEW

**Review by andvirga — APPROVED** [review]
Looks good!

**Comment by murilovmachado** [comment]
> Jira: https://bugs.benetech.org/browse/CHI-333
> 
> This PR modifies the form in local state before sending it to the backend. The only field that is nested at this point is `name` (caller & child info), in order to preserve the current code for search in the backend.

Actually `phone1` and `phone2` (this latest I think doesn't exist anymore) is also a nested field on `location` (caller & child Info). Can you check if searching for phones still works @GPaoloni ?

Besides that, the code looks fine.

**Comment by nickhurlburt** [comment]
@GPaoloni one thing we've discussed is adding the form version into the JSON sent to the backend.  In which task/PR will that be included?

**Comment by GPaoloni** [comment]
@nickhurlburt The form version is included in this PR, in ContactService file. I'm using a string as the version identifier for flexibility, is that ok?
Screenshot from 2020-12-17 11-04-56

**Comment by nickhurlburt** [comment]
Great!  I just didn't see it.

**Pull request merged**
