### PR TITLE
Api versioning

### PR DESCRIPTION
**Pull request by GPaoloni**
Jira: https://bugs.benetech.org/browse/CHI-308
This PR is related to https://github.com/tech-matters/hrm/pull/82

Primary reviewer: @murilovmachado 

This PR makes use of the new versioned backend API. Property `hrm_api_version` with value `v0` already added to our Twilio account configuration.

### CODE REVIEW

**Review by murilovmachado — APPROVED** [review]
Looks good. Does this need any backend work to be merged before?

**Comment by GPaoloni** [comment]
@murilovmachado Yes, it depends on the PR linked in the description (https://github.com/tech-matters/hrm/pull/82).

**Review by andvirga — APPROVED** [review]
This looks good, I'll also take a look at HRM

**Review by nickhurlburt — APPROVED** [review]
Great!

**Comment by GPaoloni** [comment]
Deployed to staging.

**Pull request merged**
